platform=android
appium.server=http://127.0.0.1:4723
android.deviceName=emulator-5554
android.platformName=Android
android.automationName=UiAutomator2
android.app=D:\\ckw\\apps\\application-android.apk
ios.deviceName=iPhone 16
ios.platformName=iOS
ios.automationName=XCUITest
ios.app=apps/application-ios.app
implicit.wait=10
explicit.wait=20